//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Araclar
    {
        public int AracID { get; set; }
        public Nullable<int> KoltukID { get; set; }
        public string Marka { get; set; }
        public Nullable<int> PlakaID { get; set; }
    }
}
