//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_şoförler
    {
        public int SöförID { get; set; }
        public string Söförad { get; set; }
        public string Söförsoyad { get; set; }
        public Nullable<int> AraçID { get; set; }
        public Nullable<double> TotalTutar { get; set; }
    }
}
